language: python
python:
- '3.6'
install:
- pip install pipenv
- pipenv install
script:
- python setup.py test
deploy:
  provider: pypi
  user: "DQinYuan"
  password:
    secure: bCZx16cLmpyiZxmoFIjVR7uWC9ENo5VP88iP9OKq9sO/2vvpZvGS8JEro8okCXFKllu1HNbxxSUk+GRru2XB7ya2lytzPc0VvSXxg4PodpjLDJgWjcBpbtzut+iO8AuFIKSPG2ufcNlBSNiZHst6bKXFZvtCPZD4GbQcEdkdmJmDNxaxqRZeKJChECdKey1Va1pvvz3OEZ82ZheRhQZlt88ukUF/eNMZm/wfsVSPjk2FZRf3hv9yH1ind0w0aZ+PHr5hCU2QUX3v3jpFWuBcZ8Ql7GyHfTL7dQsTdxlaCGjHmiGW+ckKYWGVrLohrflFtYBDQ6dcbASDz3HODaQ6d/61JVrD8SAVyMr5dDPd/qveiqvQZSxPiSzUH6A+k+ImquAN5C07/rshCrxIlYkB6gU8iJchSKvaxbilwMAsqW8HCxk12zHeYLQZDXKkTv/QL2ApHTuQPnlwzBIBKe/Y7yWRGXgUHvkSRTee+DTn8xZps9CVGfBi/ZM4wm5bUvhLi2lC0cUjFABURpaIW+htO4c9rPZbzw4bRj3stZXb5ot3sd87wEqFvq1BeLoCHtgOFfzl26pT08yGif7pI+zqV5SKBa4bvYc4aeh3+Ip+HFreT04Pew3xZMNgbFoPorTHNWY5O5h6eJBMRskUygCiSREMem6jmqGNcUZyfNHT9Nw=
